config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  root :to => 'home#index'
  resources :destinations, :tours, :pages, :tour_orders
  match 'home(/:action)' => 'home'
  
  namespace :admin do
    match 'destinations/photos' => 'destinations#photos'
    match 'destinations/photos_reset' => 'destinations#photos_reset'
    resources :destinations
    resources :pages
    resources :shop_orders
    resources :tours do
      match 'destinations' => 'tours#destinations'
      resources :spots do
        collection do
          post :update_positions
        end
      end
    end
    match 'schedules/generate(/:op)' => 'schedules#generate'
    resources :schedules
    resources :hotels
    resources :locations
    resources :companies
    resources :employees
    resources :customers
    resources :vehicles
    resources :user_infos
    resources :gen_schedules, :only => :index
    
  end
  match ':controller/:id/:action', :controller => /admin\/[^\/]+/
end

app/models/infos/location.rb
class Infos::Location < InfosDb
  has_many :locs, :class_name => 'Location', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'Location'
end

app/models/location.rb
class Location < InfosDb
  has_many :locs, :class_name => 'Location', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'Location'
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::ResourceController


	private
	def collection
    return @collection if @collection.present?
    
    pagination_options = {
                            :per_page  => Spree::Config[:admin_products_per_page],
                            :page      => params[:page]
                         }
                            
    @search = Location.search(params[:search])
    @collection = @search.paginate(pagination_options)

  
  end
	
end

app/views/admin/locations/_form.html.erb
<%= form_for([:admin, @location], :remote => true) do |f| %>

	<div>
		<%= f.field_container :abbr do %>
			<%= f.label :abbr %><br />
			<%= f.text_field :abbr %>
		<% end %>
	</div>
	<div class="yui-g">
		<div class="yui-u first">
		  <%= f.field_container :title do %>
		    <%= f.label :title %><br />
		    <%= f.text_field :title %>
		  <% end %>
  	</div>
  	<div class="yui-u">
		  <%= f.field_container :title_cn do %>
		    <%= f.label :title_cn %><br />
		    <%= f.text_field :title_cn %>
		  <% end %>
  	</div>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/locations/_location.html.erb
<tr id="<%= dom_id location%>">
	<td><%= location.id %></td>
	<td><%= location.abbr %></td>
	<td><%= location.title %></td>
	<td><%= location.title_cn %></td>
	<td>
		<%= link_to 'Show', admin_location_path(location) %> |
		<%= link_to 'Edit', edit_admin_location_path(location), :remote => true %> |
		<%= link_to 'Destroy', admin_location_path(location), :confirm => 'Are you sure?', :method => :delete, :remote => true %>
	</td>
</tr>

app/views/admin/locations/create.js.erb
$('<%= escape_javascript(render(:partial => @location))%>').appendTo('#locations');
$("#new_location")[0].reset();

app/views/admin/locations/edit.js.erb
$("#form > form").replaceWith("<%= escape_javascript(render(:partial => "form"))%>");
$('#edit_div').dialog('option', 'title', 'Destination ID: <%= @location.id %> (edit)').dialog('open');

app/views/admin/locations/index.html.erb
<% content_for :head do %>
<script type="text/javascript">
$(function(){
	$('#edit_div').dialog({ autoOpen: false, width: 600});
});
</script>
<% end %>
<%= render :partial => 'admin/shared/product_sub_menu' %>

<div class="toolbar">
  <ul class="actions">
  	<li>
  		<%= form_for [:admin, @search] do |f| %>
  		<%= f.label :title_contains, "Title" %> <%= f.text_field :title_contains, :size => 15 %> &nbsp;
  		<%= button t('search') %>
			<% end %>
  	</li>
    <li id="edit_location_link">
      <a href="locations/new" class="button" data-remote="true" id="admin_edit_location">
      	<span><img alt="Add" src="/images/admin/icons/add.png?1305355888"> New location</span></a>
    </li>
  </ul>
  <br class="clear">
</div>

<div id="edit_div" style="display:none;">
	<div id="form"><form></form></div>
</div>

<table class="index" id="locations">
  <tr>
    <th><%= t("id") %></th>
    <th><%= t("abbr") %></th>
		<th><%= t("title") %></th>
		<th><%= t("title_cn") %></th>
	  <th>operate</th>
  </tr>
	<% @collection.each do |location| %>
		<%= render location %>
	<% end %>
</table>
<%= will_paginate(@collection, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>

app/views/admin/locations/new.js.erb
$("#form > form").replaceWith("<%= escape_javascript(render(:partial => "form"))%>");
$('#edit_div').dialog('option', 'title', 'New location *').dialog('open');

app/views/admin/locations/show.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<h1><%= t('location')%></h1>

<p>
	<b>Title:</b> <%= @location.title %>
	<b>Title cn:</b> <%= @location.title_cn %>
</p>

app/views/admin/locations/update.js.erb
$("#<%= dom_id(@location) %>").replaceWith("<%= escape_javascript(render(:partial => @location)) %>");
<% @location = Location.new # reset for new form %>
$(".edit_location").replaceWith("<%= escape_javascript(render(:partial => "form"))%>")
$(".new_dlocation")[0].reset();
$("#edit_div").dialog('close');