config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  root :to => 'home#index'
  resources :destinations, :tours, :pages, :tour_orders
  match 'home(/:action)' => 'home'
  
  namespace :admin do
    match 'destinations/photos' => 'destinations#photos'
    match 'destinations/photos_reset' => 'destinations#photos_reset'
    resources :destinations
    resources :pages
    resources :shop_orders
    resources :tours do
      match 'destinations' => 'tours#destinations'
      resources :spots do
        collection do
          post :update_positions
        end
      end
    end
    match 'schedules/generate(/:op)' => 'schedules#generate'
    resources :schedules
    resources :hotels
    resources :locations
    resources :companies
    resources :employees
    resources :customers
    resources :vehicles
    resources :user_infos
    resources :gen_schedules, :only => :index
    
  end
  match ':controller/:id/:action', :controller => /admin\/[^\/]+/
end

app/models/infos/tour.rb
class Infos::Tour < InfosDb
  has_one :description, :as => :desc_data, :dependent => :destroy
  accepts_nested_attributes_for :description, :allow_destroy => true
  has_many :spots, :order => 'visit_day, visit_order'
  belongs_to :title_photo, :class_name => 'Infos::Photo'
  
  has_one :tour_setting, :dependent => :destroy
  accepts_nested_attributes_for :tour_setting, :allow_destroy => true
  has_one :tour_price, :dependent => :destroy
  accepts_nested_attributes_for :tour_price, :allow_destroy => true
  
  has_many :schedules, :class_name => 'Operates::Schedule'
  has_many :active_schedules, :class_name => 'Operates::Schedule', :conditions => ['departure_date > ?', Date.today + 1]
  
  def gen_schedule(day)
    return if !day || self.schedules.exists?(:departure_date => day)
    
    s = self.schedules.build
    s.departure_date = day
    s.return_date = day + days
    s.status = 1
    p = s.build_price
    if self.tour_price
      tp = self.tour_price
      p.price_adult = tp.price_adult
      p.price_child = tp.price_child
      p.price1 = tp.price1
      p.price2 = tp.price2
      p.price3 = tp.price3
      p.price4 = tp.price4
    end
    s.save    
  end
    
end

app/models/tour.rb
class Tour < InfosDb
  has_one :description, :as => :desc_data, :dependent => :destroy
  accepts_nested_attributes_for :description, :allow_destroy => true
  has_many :spots, :order => 'visit_day, visit_order'
  
  has_one :tour_setting, :dependent => :destroy
  accepts_nested_attributes_for :tour_setting, :allow_destroy => true
  has_one :tour_price, :dependent => :destroy
  accepts_nested_attributes_for :tour_price, :allow_destroy => true
  
  has_many :schedules, :conditions => ['departure_date > ?', Date.today + 1]
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::BaseController
  
  def destinations
    @tour = Infos::Tour.find(params[:tour_id])
  end
  
	def index
    return @collection if @collection.present?
    
    pagination_options = {
                            :per_page  => Spree::Config[:admin_products_per_page],
                            :page      => params[:page]}
                            
    @search = Infos::Tour.search(params[:search])
    @collection = @search.paginate(pagination_options)
  end
  def edit
    @infos_tour = Infos::Tour.find(params[:id])
  end
  def update
    @infos_tour = Infos::Tour.find(params[:id])
    @infos_tour.update_attributes(params[:id])
  end
  def destroy
    @infos_tour = Infos::Tour.find(params[:id])
    if @infos_tour.status && @infos_tour.status > 0
      @infos_tour.status = 0
    else
      @infos_tour.status = 1
    end
    @infos_tour.save
  end
  
end

app/controllers/tours_controller.rb
class ToursController < Spree::BaseController

  def index
     @tours = Infos::Tour.where('status=1').order('days')
  end

  def show
    if (params[:id] == 'bus')
      @tours = Infos::Tour.where('status=1 and tour_type=1').order('days')
      render :index
      return
    end
    if (params[:id] == 'package')
      @tours = Infos::Tour.where('status=1 and tour_type=2').order('days')
      render :index
      return
    end
    if (params[:id] == 'cruise')
      @tours = Infos::Tour.where('status=1 and tour_type=3').order('days')
      render :index
      return
    end
    @tour = Infos::Tour.find(params[:id])
  end

end

app/helpers/tours_helper.rb
module ToursHelper
  def day_night_text(day)
    if day <1
      ""
    else
      if day > 2
        "#{day} days #{day - 1} nights"
      else
        if day > 1
          "#{day} days #{day - 1} night"
        else
          "1 day"
        end
      end
    end
  end
end

app/views/admin/tours/_form.html.erb
<%= form_for( @infos_tour, :url => admin_tour_path(@infos_tour), :remote => true) do |f| %>
	<%= render :partial => 'admin/shared/title', :locals => {:f => f} %>
  <div class="yui-g">
  	<div class='yui-u first'>
	  <%= f.field_container :tour_type do %>
	  	<%= f.label :tour_type %><br />
	  	<%= f.text_field :tour_type %>
	  <% end %>
	  </div>
	  <div class='yui-u'>
	  <%= f.field_container :days do %>
	  	<%= f.label :days %><br />
	  	<%= f.text_field :days %>
	  <% end %>
	  </div>
	</div>
	<%= render :partial => 'tour_setting', :locals => {:f => f} %>
	<%= render :partial => 'tour_price', :locals => {:f => f} %>
	<%= render :partial => 'admin/shared/status', :locals => {:f => f} %>	

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/tours/_tour.html.erb
<tr id="<%= dom_id tour%>" <%= 'class=\'deleted\'' if !tour.status || tour.status < 1 %>>
	<td><%= tour.id %></td>
	<td><%= tour.title %><br /><%= tour.title_cn %></td>
	<td><%= tour.tour_type %></td>
	<td><%= tour.days %></td>
	<td><%= tour.tour_setting.weekly if tour.tour_setting %></td>
	<td><%= "#{tour.tour_price.price_adult} / #{tour.tour_price.price_child}" if tour.tour_price %></td>
	<td><%= tour.tour_setting.available_days if tour.tour_setting %></td>
	<td><%= tour.tour_setting.last_schedule_date if tour.tour_setting %></td>
	<td><%= tour.status %></td>
	<td nowrap="nowrap">
		<%= link_to 'Route', admin_tour_spots_path(tour) %> |
		<%= link_to 'Edit', edit_admin_tour_path(tour), :remote => true %> |
		<%= link_to 'Hide', admin_tour_path(tour), :remote => true, 'data-method' => 'delete', 'data-confirm' => 'Are you sure to hide/show this Tour?' %>
	</td>
</tr>

app/views/admin/tours/_tour_price.html.erb
<% @infos_tour.build_tour_price if !@infos_tour.tour_price %>
<%= f.fields_for :tour_price do |s| %>
  <div class="yui-g">
		<div class="yui-u first">
	  <%= f.field_container :price_adult do %>
	  	<%= s.label :price_adult %><br />
	  	<%= s.text_field :price_adult %>
	  <% end %>
	  
	  <%= f.field_container :price_child do %>
	  	<%= s.label :price_child %><br />
	  	<%= s.text_field :price_child %>
	  <% end %>
		</div>
		<div class='yui-u'>
	  <%= f.field_container :price1 do %>
	  	<%= s.label :price1 %><br />
	  	<%= s.text_field :price1 %>
	  <% end %>
	  
	  <%= f.field_container :price2 do %>
	  	<%= s.label :price2 %><br />
	  	<%= s.text_field :price2 %>
	  <% end %>
	  
	  <%= f.field_container :price3 do %>
	  	<%= s.label :price3 %><br />
	  	<%= s.text_field :price3 %>
	  <% end %>
		</div>
	</div>
<% end %>

app/views/admin/tours/_tour_setting.html.erb
<% @infos_tour.build_tour_setting if !@infos_tour.tour_setting %>
<%= f.fields_for :tour_setting do |s| %>
  <div class="yui-g">
		<div class="yui-u first">
	  <%= f.field_container :weekly do %>
	  	<%= s.label :weekly %><br />
	  	<%= s.text_field :weekly %>
	  <% end %>
	  <%= f.field_container :is_auto_gen do %>
	  	<%= s.label :is_auto_gen %><br />
	  	<%= s.text_field :is_auto_gen %>
	  <% end %>
	  </div>
	  <div class='yui-u'>
	  <%= f.field_container :has_seat_table do %>
	  	<%= s.label :has_seat_table %><br />
	  	<%= s.text_field :has_seat_table %>
	  <% end %>
	  <%= f.field_container :is_float_price do %>
	  	<%= s.label :is_float_price %><br />
	  	<%= s.text_field :is_float_price %>
	  <% end %>
		</div>
	</div>
<% end %>

app/views/admin/tours/create.js.erb
$('<%= escape_javascript(render(:partial => @tour))%>').appendTo('#tours');
$("#new_destination")[0].reset();

app/views/admin/tours/destinations.html.erb
<% content_for :head do %>
<script type="text/javascript">
$(function(){
	$('#edit_div').dialog({ autoOpen: false, width: 700});
});
</script>
<% end %>
<%= render :partial => 'admin/shared/product_sub_menu' %>

<div class="toolbar">
  <ul class="actions">
    <li id="edit_tour_link">
      <a href="tours/new" class="button" data-remote="true" id="admin_edit_tour">
      	<span><img alt="Add" src="/images/admin/icons/add.png?1305355888">New Tour</span></a>
    </li>
  </ul>
  <br class="clear">
</div>

<div id="edit_div" style="display:none;">
<div id="form"><form></form></div>
</div>

<table class="index" id="tours">
  <tr>
    <th><%= t("id") %></th>
	<th><%= t("title") %></th>
	<th><%= t("created_at")%></th>
	<th><%= t("updated_at")%></th>
	<th><%= t("status")%></th>
  <th>operate</th>
  </tr>
<% @tour.destinations_tours.each do |td| %>
	<%= render 'tour_dest', :td => td %>
<% end %>
</table>

app/views/admin/tours/destroy.js.erb
$("#<%= dom_id(@infos_tour) %>")
	.replaceWith("<%= escape_javascript(render(:partial => 'tour', :locals => {:tour => @infos_tour})) %>");

$("#edit_div").dialog('close');

app/views/admin/tours/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/admin/tours/edit.js.erb
$("#form > form").replaceWith("<%= escape_javascript(render(:partial => "form"))%>");
$('#edit_div').dialog('open');

app/views/admin/tours/index.html.erb
<% content_for :head do %>
<script type="text/javascript">
$(function(){
	$('#edit_div').dialog({ autoOpen: false, width: 700});
});
</script>
<% end %>
<%= render :partial => 'admin/shared/product_sub_menu' %>

<div class="toolbar">
  <ul class="actions">
  	<li>
  		<%= form_for( @search, :url => admin_tours_path ) do |f| %>
  		<%= f.label :title_contains, "Title" %> <%= f.text_field :title_contains, :size => 15 %> &nbsp;
  		<%= button t('search') %>
			<% end %>
  	</li>
    <li id="edit_tour_link">
      <a href="tours/new" class="button" data-remote="true" id="admin_edit_tour">
      	<span><img alt="Add" src="/images/admin/icons/add.png?1305355888"> New Tour</span></a>
    </li>
  </ul>
  <br class="clear">
</div>

<div id="edit_div" style="display:none;">
<div id="form"><form></form></div>
</div>

<table class="index" id="tours">
  <tr>
    <th><%= t("id") %></th>
	<th><%= t("title") %></th>
	<th><%= t("tour_type")%></th>
	<th>days</th>
	<th>weekly</th>
	<th>price</th>
	<th><%= t("available_days")%></th>
	<th><%= t("last_schedule_date")%></th>
	<th><%= t("status")%></th>
  <th>operate</th>
  </tr>
<% @collection.each do |tour| %>
	<%= render :partial => 'tour', :locals => {:tour => tour} %>
<% end %>
</table>
<%= will_paginate(@collection, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;") %>

app/views/admin/tours/new.js.erb
$("#form > form").replaceWith("<%= escape_javascript(render(:partial => "form"))%>");
$('#edit_div').dialog('option', 'title', 'New Tour *').dialog('open');

app/views/admin/tours/update.js.erb
$("#edit_div").dialog('close');