config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  root :to => 'home#index'
  resources :destinations, :tours, :pages, :tour_orders
  match 'home(/:action)' => 'home'
  
  namespace :admin do
    match 'destinations/photos' => 'destinations#photos'
    match 'destinations/photos_reset' => 'destinations#photos_reset'
    resources :destinations
    resources :pages
    resources :shop_orders
    resources :tours do
      match 'destinations' => 'tours#destinations'
      resources :spots do
        collection do
          post :update_positions
        end
      end
    end
    match 'schedules/generate(/:op)' => 'schedules#generate'
    resources :schedules
    resources :hotels
    resources :locations
    resources :companies
    resources :employees
    resources :customers
    resources :vehicles
    resources :user_infos
    resources :gen_schedules, :only => :index
    
  end
  match ':controller/:id/:action', :controller => /admin\/[^\/]+/
end

app/controllers/tour_orders_controller.rb
class TourOrdersController < Spree::BaseController
  def new
    redirect_back_or_default '/login' if !current_user
    @tour = Tour.find(params[:tour])
    @order = ShopOrder.new
    @order.order_items.build
    @datelist = @tour.schedules.map {|s| '[' + s.departure_date.strftime('%Y.%m.%d')+ ']'}.join()
    @max_date = (@tour.schedules.last.departure_date.to_date - Date.today).to_i
  end
  
  def edit
    @order = ShopOrder.find(params[:id])
    @tour = @order.schedule.tour
  end
  
  def create
    @order = ShopOrder.new(params[:shop_order])
    @order.save!
    
    redirect_to edit_tour_order_path(@order)
  end
    
end

app/views/tour_orders/_room.html.erb
<div>
	Room #: 
	Adult: <%= item.text_field :num_adult, :size => 2 %> 
	Child: <%= item.text_field :num_child, :size => 2 %>
</div>

app/views/tour_orders/edit.html.erb
<%= content_for :head do %>
<script type='text/javascript'>
	function add_room(){
		alert('add room');
	}
</script>
<% end %>

<h1>New Order</h1>

<%= form_for @order, :url => tour_orders_url do |f| %>
	<p>
		[<b><%= @tour.id %></b>]
		<%= @tour.title %>
	</p>>
	
	<p>
		<%= f.select :schedule_id, @tour.schedules.collect{|s| [s.departure_date.strftime('%a, %b %d, %Y'), s.id]} %>
	</p>
	
    	<% f.fields_for :order_items do |item| %>
				<%= render :partial => 'room', :locals => {:item => item} %>
    	<% end %>
	<p>
		<input type='button' value="add room" onclick="add_room();" />
	</p>
	
	<p>
		<%= f.submit 'submit' %>
	</p>

<% end %>

app/views/tour_orders/new.html.erb
<%= content_for :head do %>
<%= javascript_include_tag 'jqueryui/jquery-ui-1.8.13.custom.min.js' %>
<%= stylesheet_link_tag '/javascripts/jqueryui/jquery-ui-1.8.13.custom.css' %>

<script type='text/javascript'>
var room_count = 100;

function add_room(){
	room_count++;
	var nm = 'shop_order[order_items_attributes]['+ room_count + ']';
	var item = "<div>Room #: Adult: <input name='" + nm + "[num_adult]' type='text' size='2' /> Child: <input name='" + nm + "[num_child]' type='text' size='2' /> <a onclick='rm_room(this);'>remove</a><br /></div>";
	item = $(item);
//	  item.find('a').click(function(){ alert($(this).parent().text()); });
	$('#rooms').append(item);
	item.show('slide', {direction: 'up'}, 500, null);
}
var current_node = null;	
	function rm_room(nd){
		var node = $(nd).parent();
		node.find('input').val('');
		node.hide('slide',{direction: 'up'}, 500, null);
	}
	
$(function(){
	$('a.add_room').click(function(){
		add_room();
	});
	
	var vds = '<%= @datelist %>';
	
	$('#departure').datepicker({
		numberOfMonths: 3,
		showButtonPanel: false,
		minDate: 0,
		maxDate: <%= @max_date %>,
		beforeShowDay: function(date){
			var m = date.getMonth() + 1;
			if (m < 10)
				m = "0" + m;
			else
				m = '' + m;
			var s = '[' + date.getFullYear() + '.' + m + '.' + date.getDate() + ']';
			if (vds.indexOf(s)<0)
				return [0, '', null];
			else
				return [1, '', s];	
		}
	});
});
</script>
<% end %>

<h1>New Order</h1>

<%= form_for @order, :url => tour_orders_url do |f| %>
	<p>
		[<b><%= @tour.id %></b>]
		<%= @tour.title %>
	</p>>
	
	<p>
		<%= f.select :schedule_id, @tour.schedules.collect{|s| [s.departure_date.strftime('%a, %b %d, %Y'), s.id]} %>
	</p>
	
	<p>
		Departure at: <input type='text' id='departure' />
	</p>
	
	<div id='rooms'>
    	<%= f.fields_for :order_items do |item| %>
				<%= render :partial => 'room', :locals => {:item => item} %>
    	<% end %>
  </div>
	<p>
		<%= link_to "Add room", 'javascript:add_room()' %>
	</p>
	
	<p>
		<%= f.submit 'submit' %>
	</p>

<% end %>