config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  root :to => 'home#index'
  resources :destinations, :tours, :pages, :tour_orders
  match 'home(/:action)' => 'home'
  
  namespace :admin do
    match 'destinations/photos' => 'destinations#photos'
    match 'destinations/photos_reset' => 'destinations#photos_reset'
    resources :destinations
    resources :pages
    resources :shop_orders
    resources :tours do
      match 'destinations' => 'tours#destinations'
      resources :spots do
        collection do
          post :update_positions
        end
      end
    end
    match 'schedules/generate(/:op)' => 'schedules#generate'
    resources :schedules
    resources :hotels
    resources :locations
    resources :companies
    resources :employees
    resources :customers
    resources :vehicles
    resources :user_infos
    resources :gen_schedules, :only => :index
    
  end
  match ':controller/:id/:action', :controller => /admin\/[^\/]+/
end

app/models/infos/photo.rb
class Infos::Photo < InfosDb
  belongs_to :photo_data, :polymorphic => true
end

app/models/photo.rb
class Photo < InfosDb
  belongs_to :photo_data, :polymorphic => true
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::ResourceController

  create.after :create_after

  def create_after
    if params[:destination_id]
      @destination = Destination.find(params[:destination_id])
      @destination.photos << @photo
    end
  end
  def location_after_save
    admin_destination_photos_url(@destination)
  end
  
  def cover
    @destination = Destination.find(params[:destination_id])
    @destination.photo_id = params[:photo_id]
    @destination.save
  end
    
	private
	def load_data
		if params[:destination_id]
    	@destination = Destination.find(params[:destination_id])
    end
  end
	def collection
    return @collection if @collection.present?
    if params[:destination_id]
      @destination = Destination.find(params[:destination_id])
      @collection = @destination.photos
    end
    
    # pagination_options = {
                            # :per_page  => Spree::Config[:admin_products_per_page],
                            # :page      => params[:page]}
#                             
    # @search = Photo.search(params[:search])
    # @collection = @search.paginate(pagination_options)
  end
	
end

app/views/admin/photos/_form.html.erb
<tr>
  <td><%= t("filename") %>:</td>
  <td><%= f.file_field :attachment %></td>
</tr>
<tr>
  <td><%= t("alt_text") %>:</td>
  <td><%= f.text_field :alt %></td>
</tr>

app/views/admin/photos/_new111.html.erb
<h4><%= t("new_photo") %></h4>
<%= form_for(:photo, :url => { :controller => 'photos', :action => 'create' }, :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render :partial => "form", :locals => { :f => form } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>


<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_photo_link').show();
    jQuery('#photos').html('');
  });  
 
</script>

app/views/admin/photos/cover.js.erb
$('#dest_photo').attr('src', '<%= @destination.photo.attachment.url(:mini) %>');

app/views/admin/photos/edit.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render "shared/error_messages", :target => @photo %>
<%= form_for(:photo, :url => admin_destination_photo_url(@destination), :html => { :method => :put, :multipart => true }) do |f| %>
  <table class="basic-table" style='width:auto;'>
    <tr>
      <td><%= t("thumbnail") %>:</td>
      <td><%= link_to(image_tag(@photo.attachment.url(:mini)), @photo.attachment.url(:destination)) %></td>
    </tr>
    <%= render :partial => "form", :locals => { :f => f } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), admin_destination_photos_url(@destination), :id => "cancel_link" %>
  </p>
<% end %>

app/views/admin/photos/index.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li id="new_photo_link">
      <%= button_link_to t("new_photo"), new_admin_destination_photo_path, {:remote => true, :icon => 'add', :id => 'admin_new_photo'} %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= image_tag( (@destination.photo ? @destination.photo.attachment.url(:mini) : 'coming_soon_100.png'), :style => 'border:solid 1px #aaa;padding:1px;', :id => 'dest_photo') %><%= "#{@destination.title}/#{@destination.title_cn}" %></h1>
<%= link_to 'Back to destinations list', '../photos' %>
<div id="new_photo"></div>

<div>
<% @collection.each do |p| %>
	<div style="width:150px;height:300px;float:left;border:solid 1px #999; padding:4px;margin:4px;">
		<%= image_tag p.attachment.url(:small) %><br />
		<div><%= p.attachment_file_name %></div>
		<div><%= p.alt %></div>
		<div>
        <%= link_to image_tag('/images/admin/icons/edit.png') + 'Edit', edit_admin_destination_photo_path(@destination, p), :class => 'edit'   %>
        &nbsp;|&nbsp;
        <%= link_to_delete p  %><br />
        <%= link_to 'Set as cover', "photos/#{p.id}/cover", {:remote => true, :icon => 'add'} %>
		</div>
	</div>  
<% end %>
	<div class='clear'></div>
</div>

app/views/admin/photos/new.html.erb
<h4><%= t("new_photo") %></h4>
<%= form_for(:photo, :url => { :controller => 'photos', :action => 'create' }, :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render :partial => "form", :locals => { :f => form } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>

<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_spot_link').show();
    jQuery('#new_spot').html('');
  });
</script>

app/views/admin/photos/show.html.erb
<h1>Show</h1>